---
version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - benchmem
  - benchtime
  - containedctx
  - contextcheck
  - cyclop
  - daixiang
  - ewrap
  - funlen
  - GITVERSION
  - goarch
  - GOFILES
  - gofumpt
  - gosec
  - honnef
  - mvdan
  - Newf
  - nolint
  - NOVENDOR
  - randv
  - Retryable
  - staticcheck
  - venv
  - Wrapf
ignoreWords: []
import: []
